# Generated by Django 2.2.1 on 2019-06-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.CharField(max_length=100)),
                ('cop', models.CharField(max_length=200)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Commodity')),
            ],
        ),
    ]
