# Generated by Django 2.2.1 on 2019-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
